---
AWSTemplateFormatVersion: '2010-09-09'
Description: Creates an S3 bucket configured for hosting a static website

Parameters:
  FullDomainName:
    Type: String    
    Default: ''
    Description: The full domain name. Mutually exclusive with Aliases
    AllowedPattern: (^$|(?!-)[a-zA-Z0-9-.]{1,63}(?<!-))
  AcmCertificateArn:
    Type: String
    Default: ''
    Description: The Amazon Resource Name (ARN) of an AWS Certificate Manager (ACM) certificate.
  IAMDeployUser:
    Type: String
    Default: ''
    Description: The IAM user that is allowed to deploy content
  IAMRole:
    Type: String
    Default: ''
    Description: IAM Role Name for IAM Policy Attachment
  CreateCloudfront:
    Type: String
    AllowedValues: ['true', 'false']
    Default: 'true'
    Description: IAM Role Name for IAM Policy Attachment
  DefaultDocument:
    Type: String
    Default: index.html
    Description: Default filename to render
  ErrorDocument:
    Type: String
    Default: '404.html'
    Description: Filename to use for errors

  CustomBucketArn:
    Type: String
    Default: ''
    Description: Optionally, use a pre-existing bucket by providing its Arn attribute
  CustomBucketWebsiteURL:
    Type: String
    Default: ''
    Description: Optionally, use a pre-existing bucket by providing its WebsiteURL attribute

  TableReadCapacity:
    Type: Number
    Description: Read capacity for the DynamoDB blog table.
    Default: '3'
    MinValue: 1
  TableWriteCapacity:
    Type: Number
    Description: Write capacity for the DynamoDB blog table.
    Default: '3'
    MinValue: 1

Outputs:
  JournalTableName:
    Value: !Ref JournalTable

Resources:
  S3WebsiteStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        FullDomainName: !Ref FullDomainName
        AcmCertificateArn: !Ref AcmCertificateArn
        MinTlsVersion: 'TLSv1'
        IAMDeployUser: !Ref IAMDeployUser
        IAMRole: !Ref IAMRole
        CreateCloudfront: !Ref CreateCloudfront
        SiteIsVueJs: 'true'
        DefaultDocument: !Ref DefaultDocument
        ErrorDocument: !Ref ErrorDocument
        CustomBucketArn: !Ref CustomBucketArn
        CustomBucketWebsiteURL: !Ref CustomBucketWebsiteURL
      TemplateURL: https://s3.amazonaws.com/digops-stacks/version/16.9.0/s3-static-site.template

  JournalTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
      KeySchema:
        - AttributeName: Id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref TableReadCapacity
        WriteCapacityUnits: !Ref TableWriteCapacity